
apiVersion: discovery.k8s.io/v1beta1
kind: EndpointSlice
metadata:
  name: example-abc
  labels:
    kubernetes.io/service-name: simple-node-entrypoint
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - "169.254.169.254"
    conditions:
      ready: true
    hostname: pod-1018
    topology:
      kubernetes.io/hostname: node-1
      topology.kubernetes.io/zone: us-west2-a